name: Docker API Test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

  build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: incogzino
            password: ${{ secrets.GHCR_PAT }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            platforms: linux/amd64
            push: true
            tags: ghcr.io/incogzino/build-backend:latest
            cache-from: type=gha
            cache-to: type=gha