name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Clone the backend repository
    - name: Checkout Backend Repository
      uses: actions/checkout@v4
      with:
        repository: incogzino/store-api
        path: backend   

    #Install MongoDB tools
    - name: Install mongosh
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-mongosh mongodb-org-tools
    
    # MongoDB setup
    - name: MongoDB Setup
      uses: supercharge/mongodb-github-action@v1
      with:
        mongodb-version: latest

    #Load MongoDB collections 
    - name: Load products into MongoDB
      run: mongoimport --uri mongodb://localhost:27017/OutOfOrder --collection products --file ./backend/products.json --jsonArray
    - name: Load reviews into MongoDB
      run: mongoimport --uri mongodb://localhost:27017/OutOfOrder --collection reviews --file ./backend/reviews.json --jsonArray

    #Frontend dependencies installed    
    - name: Install dependencies
      run: npm ci
 
    # Install backend dependencies
    - name: Install Backend Dependencies
      run: npm ci
      working-directory: ./backend  

    # Running API
    - name: Run API
      run: npm start  

    #Playwright dependencies installed 
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    #Playwright tests
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
